CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    department VARCHAR(255),
    salary NUMERIC(38,2),
    hire_date DATE,
    PRIMARY KEY (id)
);
