CREATE SEQUENCE revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY,
    revtstmp BIGINT,
    PRIMARY KEY (rev)
);

CREATE TABLE employee_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    department VARCHAR(255),
    salary NUMERIC(38,2),
    hire_date DATE,
    PRIMARY KEY (rev, id),
    CONSTRAINT fk_employee_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE app_user_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    username VARCHAR(255),
    password_hash VARCHAR(255),
    role VARCHAR(20),
    PRIMARY KEY (rev, id),
    CONSTRAINT fk_app_user_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
