CREATE TABLE rag_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    filename VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    page_count INT NOT NULL,
    chunk_count INT NOT NULL,
    PRIMARY KEY (id)
);
